### ISSUE TITLE
Any demo video?

### ISSUE THREAD

**Issue by Becomebright** [ChenDelong1999/VirtualConductor#2]
Really interesting work. Could you please share some demo videos?

**Comment by ChenDelong1999** [comment]
Sure, you may check https://www.bilibili.com/video/BV1Zy4y1W7Qq and https://www.bilibili.com/video/BV1aX4y1g7wh :-)

**Comment by ChenDelong1999** [comment]
> Really interesting work. Could you please share some demo videos?

Sure, you may check https://www.bilibili.com/video/BV1Zy4y1W7Qq and https://www.bilibili.com/video/BV1aX4y1g7wh :-)

**Comment by Becomebright** [comment]
Impressing. Thanks a lot.
