### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by SutirthaChakraborty** [ChenDelong1999/VirtualConductor#3]
Hi, I am trying to download the dataset. But unable to download. Any mirror site to directly download. Thanks.

**Comment by ChenDelong1999** [comment]
Thanks for your interest. We have uploaded a copy of the dataset to Google drive.

Training split: https://drive.google.com/file/d/1w8MfhKRPTCy9FwaN3MP-njhvxWNHtLdE
Validation split: https://drive.google.com/file/d/1HUCdXcEpLf2leDCm-Q8ryKCfigBt4ZdD

**Comment by SutirthaChakraborty** [comment]
Thank you so much.

**Comment by SutirthaChakraborty** [comment]
Do you have any code to inverse the Mel to Audio?
```
import librosa
import numpy as np
import soundfile as sf
import IPython
M=np.load('/val/0/mel.npy').T
rate = 44100
audio = librosa.feature.inverse.mel_to_audio(M)
sf.write('stereo_file.wav', audio, rate, subtype='PCM_24')
IPython.display.Audio('stereo_file.wav')
```
I tried this. But getting noise. Any help?

**Comment by ChenDelong1999** [comment]
We have not tried this. The raw wave files are not going to be made public. However, we present the code to extract the spectrum, which probably can help. 

See https://github.com/ChenDelong1999/VirtualConductor/blob/main/utils/music_utils.py#L8

**Comment by SutirthaChakraborty** [comment]
Yes, I have seen that. Can you personally send me just one audio data so that I can infer some insights about the audio and video data mapping. It would be very helpful for me. If possible. 
Thank you so much.

**Comment by ChenDelong1999** [comment]
Here is an example audio: https://drive.google.com/file/d/1uOebp9E-iDSexJG5tZI20CuQcUppqVrT

Its length is 60s. If you run the[ mel extraction code](https://github.com/ChenDelong1999/VirtualConductor/blob/main/utils/music_utils.py#L8)，you will get a numpy array with a shape of (5400,128), which is same as each `mel.npy`.

**Comment by SutirthaChakraborty** [comment]
Can we get the test data 

> Thanks for your interest. We have uploaded a copy of the dataset to Google drive.
> 
> Training split: https://drive.google.com/file/d/1w8MfhKRPTCy9FwaN3MP-njhvxWNHtLdE Validation split: https://drive.google.com/file/d/1HUCdXcEpLf2leDCm-Q8ryKCfigBt4ZdD

Can we also get the test dataset please ?
