### ISSUE TITLE
Code of M2S-Net and M2S-GAN

### ISSUE THREAD

**Issue by koah-12358** [ChenDelong1999/VirtualConductor#5]
Great work.
Could you please share the codes to train M2S-Net and M2S-GAN in [your paper](https://link.springer.com/article/10.1007/s11390-022-2030-z)?

It seems that there are only codes for training and testing a plain model.

**Comment by ChenDelong1999** [comment]
Thanks for your interest in our work. Our apologies for the delayed open sourcing of our model. We will update this repo soon.

**Comment by koah-12358** [comment]
Thanks a lot.
I would be grateful if you would tell me how it will take.

**Comment by ChenDelong1999** [comment]
Unfortunately, the student who currently takes charge of this project just got appendicitis... so I think we will update the code in the next week.

**Comment by koah-12358** [comment]
Oh, I hope he or she gets well soon...

Thanks.

**Comment by SutirthaChakraborty** [comment]
Following it

**Comment by ChenDelong1999** [comment]
@RXin-he
