### ISSUE TITLE
Where is "checkpoints/M2SGAN/M2SGAN_official_pretrained.pt"

### ISSUE THREAD

**Issue by FlorenceZh** [ChenDelong1999/VirtualConductor#6]
I can't find it in this repositories.

**Comment by ChenDelong1999** [comment]
Sorry for the missing checkpoint, it has been updated now (commit https://github.com/ChenDelong1999/VirtualConductor/commit/ff9995af7bd742d4a3362916ad8be36ffff2b325).

**Comment by FlorenceZh** [comment]
thanks~~~
